/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio;

import static Inicio.MySql.empleadoBuscar;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;




import org.apache.commons.io.FileUtils;


public class Mostrar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Mostrar
     */
    public Mostrar() {
        initComponents();
        holder();
        nss(txtNss);
        nuevonss(txtNuevonss);
        cuenta(txtCuenta);
        otro(txtOtro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblPaterno = new javax.swing.JLabel();
        lblMaterno = new javax.swing.JLabel();
        lblFechaNac = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCurp = new javax.swing.JTextField();
        txtNss = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblFechaNac1 = new javax.swing.JLabel();
        txtRfc = new javax.swing.JTextField();
        lblFechaNac2 = new javax.swing.JLabel();
        txtNuevonss = new javax.swing.JTextField();
        lblFechaNac3 = new javax.swing.JLabel();
        lblFechaNac4 = new javax.swing.JLabel();
        txtEstudios = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        lblFechaNac5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblFechaNac6 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        lblFechaNac7 = new javax.swing.JLabel();
        lblFechaNac8 = new javax.swing.JLabel();
        txtOtro = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        lblFechaNac9 = new javax.swing.JLabel();
        lblFechaNac10 = new javax.swing.JLabel();
        txtEmergencia = new javax.swing.JTextField();
        lblFechaNac11 = new javax.swing.JLabel();
        txtComentarios = new javax.swing.JTextField();
        txtHistorial = new javax.swing.JTextField();
        lblFechaNac12 = new javax.swing.JLabel();
        lblFechaNac13 = new javax.swing.JLabel();
        txtRutas = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnNomina = new javax.swing.JButton();
        lblFoto2 = new javax.swing.JLabel();
        txtRutaFoto1 = new javax.swing.JTextField();
        jcbOrigen = new javax.swing.JComboBox<>();
        jcbRegistro = new javax.swing.JComboBox<>();
        btnReporte = new javax.swing.JButton();
        btnCarpeta = new javax.swing.JButton();
        txtCarpeta = new javax.swing.JTextField();
        gafetesarea = new javax.swing.JPanel();
        lblPuesto = new javax.swing.JLabel();
        txtPuesto = new javax.swing.JTextField();

        setIconifiable(true);
        setMaximizable(true);
        setTitle("Mostrar Empleado");

        lblNombre.setText("Estado de registro:");

        lblPaterno.setText("Nombre:");

        lblMaterno.setText("Curp:");

        lblFechaNac.setText("Nss:");

        txtCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurpActionPerformed(evt);
            }
        });

        txtNss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNssKeyTyped(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inicio/editar.png"))); // NOI18N
        btnEditar.setText("MODIFICAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inicio/eliminar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblFechaNac1.setText("RFC");

        lblFechaNac2.setText("Nuevo Nss:");

        txtNuevonss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNuevonssKeyTyped(evt);
            }
        });

        lblFechaNac3.setText("Estado de origen:");

        lblFechaNac4.setText("Grado de estudios:");

        lblFechaNac5.setText("Correo electronico:");

        lblFechaNac6.setText("Numero de telefono:");

        lblFechaNac7.setText("Numero de cuenta:");

        lblFechaNac8.setText("Numero de OTRO banco:");

        lblFechaNac9.setText("Direccion:");

        lblFechaNac10.setText("Telefono de emergencias:");

        lblFechaNac11.setText("Comentarios/Salud:");

        lblFechaNac12.setText("Historial Laboral:");

        lblFechaNac13.setText("Rutas Asignadas:");

        txtStatus.setEditable(false);

        jLabel1.setText("Status:");

        jLabel2.setText("ID:");

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(204, 204, 204));
        txtId.setForeground(new java.awt.Color(255, 255, 255));

        btnNomina.setText("Agregar Nomina");
        btnNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNominaActionPerformed(evt);
            }
        });

        lblFoto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtRutaFoto1.setBackground(new java.awt.Color(204, 204, 204));
        txtRutaFoto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaFoto1ActionPerformed(evt);
            }
        });

        btnReporte.setText("Generar PDF");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        btnCarpeta.setText("Abrir Carpeta");
        btnCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarpetaActionPerformed(evt);
            }
        });

        txtCarpeta.setEditable(false);
        txtCarpeta.setForeground(new java.awt.Color(255, 255, 255));
        txtCarpeta.setEnabled(false);

        gafetesarea.setBorder(javax.swing.BorderFactory.createTitledBorder("Generación de gafetes."));

        btnGafete.setText("Generar Gafete");
        btnGafete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGafeteActionPerformed(evt);
            }
        });

        lblPuesto.setText("(Obligatorio) Puesto:");

        txtPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gafetesareaLayout = new javax.swing.GroupLayout(gafetesarea);
        gafetesarea.setLayout(gafetesareaLayout);
        gafetesareaLayout.setHorizontalGroup(
            gafetesareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gafetesareaLayout.createSequentialGroup()
                .addComponent(lblPuesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPuesto))
            .addGroup(gafetesareaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnGafete, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        gafetesareaLayout.setVerticalGroup(
            gafetesareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gafetesareaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(gafetesareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPuesto)
                    .addComponent(txtPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGafete)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaNac1)
                    .addComponent(lblFechaNac2)
                    .addComponent(lblFechaNac3)
                    .addComponent(lblFechaNac4)
                    .addComponent(lblFechaNac5)
                    .addComponent(lblFechaNac6)
                    .addComponent(lblFechaNac7)
                    .addComponent(lblFechaNac8)
                    .addComponent(lblFechaNac9)
                    .addComponent(lblFechaNac10)
                    .addComponent(lblFechaNac11)
                    .addComponent(lblFechaNac12)
                    .addComponent(lblFechaNac13)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblPaterno)
                            .addComponent(lblMaterno)
                            .addComponent(lblFechaNac))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(131, 131, 131)
                                        .addComponent(txtCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNomina, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtOtro, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(gafetesarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(105, 105, 105))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(155, 155, 155)
                                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                                    .addComponent(txtCurp, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                                    .addComponent(txtNss, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                                    .addComponent(jcbRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(80, 80, 80)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel1)
                                                            .addComponent(jLabel2))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                                            .addComponent(txtId)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtRutaFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtNuevonss, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jcbOrigen, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtEstudios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)))
                                                .addGap(153, 153, 153)
                                                .addComponent(btnCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 54, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(129, 129, 129))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jcbRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPaterno)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMaterno)
                                    .addComponent(txtCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFechaNac)
                                    .addComponent(txtNss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(txtRutaFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFechaNac1)
                                    .addComponent(txtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFechaNac2)
                                    .addComponent(txtNuevonss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFechaNac3)
                                    .addComponent(jcbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(btnCarpeta)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFechaNac4)
                                    .addComponent(txtEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFechaNac5)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFechaNac6)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFechaNac7)
                                    .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFechaNac8)
                                    .addComponent(txtOtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gafetesarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))))
                    .addComponent(lblFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaNac9)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaNac10)
                            .addComponent(txtEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditar)
                            .addComponent(btnEliminar))
                        .addGap(16, 16, 16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNac11)
                    .addComponent(txtComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaNac12)
                            .addComponent(txtHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaNac13)
                            .addComponent(txtRutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNomina, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addGap(59, 59, 59))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void guardar(String id,String fecha,String archivo){
            
              MySql db1 = new MySql();
        int consultaInsertar=0;
        
        try {
            db1.MySQLConnection("root","prestige", "prestige");
          
        }
        catch (Exception ex) {
            Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        consultaInsertar = db1.agregarNomina(id, fecha, archivo);
        
        
        
        
        if(consultaInsertar == 0){
            JOptionPane.showMessageDialog(null, "Registro No Insertado");
        }
        else{
            JOptionPane.showMessageDialog(null, "REGISTRO INSERTADO EXITOSAMENTE");
            
            
            
            
            
        }}
    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        MySql db1 = new MySql();
        int consulta=0;

        int sexo=0;
        String registro = (String) jcbRegistro.getSelectedItem();
        String origen = (String) jcbOrigen.getSelectedItem();
        //Asignar los datos del formulario al objeto de la clase Empleado
        empleadoBuscar.setId(Integer.parseInt(txtId.getText()));
        empleadoBuscar.setEstadoregistro(registro);
            empleadoBuscar.setNombre(txtNombre.getText());
        empleadoBuscar.setCurp(txtCurp.getText());
        empleadoBuscar.setNss(txtNss.getText());
        empleadoBuscar.setRfc(txtRfc.getText());
        empleadoBuscar.setNssnuevo(txtNuevonss.getText());
        empleadoBuscar.setOrigen(origen);
        empleadoBuscar.setEstudios(txtEstudios.getText());
        empleadoBuscar.setCorreo(txtCorreo.getText());
        empleadoBuscar.setTelefono(txtTelefono.getText());
        empleadoBuscar.setCuenta(txtCuenta.getText());
        empleadoBuscar.setOtro(txtOtro.getText());
        empleadoBuscar.setDireccion(txtDireccion.getText());
        empleadoBuscar.setEmergencia(txtEmergencia.getText());
        empleadoBuscar.setComentarios(txtComentarios.getText());
        empleadoBuscar.setHistorialLaboral(txtHistorial.getText());
        empleadoBuscar.setRutasAsignadas(txtRutas.getText());
        empleadoBuscar.setRutaFoto(txtRutaFoto1.getText());
        

        
        
        registro = null;
        origen =null;
        
        
        
        
        
        
        
        //conectar a la bd
        try {
            db1.MySQLConnection("root","prestige","prestige");
           //JOptionPane.showMessageDialog(null,paterno, "Buscar Conectar BD!!", JOptionPane.INFORMATION_MESSAGE;
           
        }
        catch (Exception ex) {
            Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Error Al conectar a la base de datos");
        }

        //llamar al método para actualizar el empleado en la BD
     



 consulta = db1.updateRegistro();




if(consulta == 0){
        JOptionPane.showMessageDialog(null, "REGISTRO NO ACTUALIZADO");
        }
        else{
        JOptionPane.showMessageDialog(null, "REGISTRO ACTUALIZADO");
        
       }

        try {
            db1.closeConnection();
        
        } catch (SQLException ex) {
            Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnEditarActionPerformed
  private void holder(){
         TextPrompt placeholder = new TextPrompt("Solo Numeros", txtNss);
         placeholder.changeAlpha(0.75f);
         placeholder.changeStyle(Font.ITALIC);
           TextPrompt placeholder1 = new TextPrompt("Solo Numeros",txtNuevonss);
          placeholder1.changeAlpha(0.75f);
         placeholder1.changeStyle(Font.ITALIC);
        TextPrompt placeholder2 = new TextPrompt("Solo Numeros",txtCuenta);
          placeholder2.changeAlpha(0.75f);
         placeholder2.changeStyle(Font.ITALIC);
        TextPrompt placeholder3 = new TextPrompt("Solo Numeros",txtOtro);
          placeholder3.changeAlpha(0.75f);
         placeholder3.changeStyle(Font.ITALIC);
        
         
        
    }
    
    
  
   private void otro(JTextField a){
        //Poner solo numeros
        a.addKeyListener(new KeyAdapter() {
       
            public void keyTyped(KeyEvent e ){
            
                char c = e.getKeyChar();
                
                if(!Character.isDigit(c)){
                    e.consume();
                }
                
                if(c == '.' && txtOtro.getText().contains(".")){
                    e.consume();
                }
            
        
        
        }});
        
        
        
        
    }
  
   private void cuenta(JTextField a){
        //Poner solo numeros
        a.addKeyListener(new KeyAdapter() {
       
            public void keyTyped(KeyEvent e ){
            
                char c = e.getKeyChar();
                
                if(!Character.isDigit(c)){
                    e.consume();
                }
                
                if(c == '.' && txtCuenta.getText().contains(".")){
                    e.consume();
                }
            
        
        
        }});
        
        
        
        
    }
  
   private void nuevonss(JTextField a){
        //Poner solo numeros
        a.addKeyListener(new KeyAdapter() {
       
            public void keyTyped(KeyEvent e ){
            
                char c = e.getKeyChar();
                
                if(!Character.isDigit(c)){
                    e.consume();
                }
                
                if(c == '.' && txtNuevonss.getText().contains(".")){
                    e.consume();
                }
            
        
        
        }});
        
        
        
        
    }
   private void nss(JTextField a){
        //Poner solo numeros
        a.addKeyListener(new KeyAdapter() {
       
            public void keyTyped(KeyEvent e ){
            
                char c = e.getKeyChar();
                
                if(!Character.isDigit(c)){
                    e.consume();
                }
                
                if(c == '.' && txtNss.getText().contains(".")){
                    e.consume();
                }
            
        
        
        }});
        
        
        
        
    }
  
  
  
  
  
  
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        MySql db1 = new MySql();
        int consulta=0;
        //conectar a la bd
        try {
        db1.MySQLConnection("root", "prestige", "prestige");
        }
        catch (Exception ex) {
        Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        //llamar al método para eliminar el empleado de manera lógica en la BD
       





 consulta = db1.eliminarRegistro();
        
       
       
       
       if(consulta == 0){
        JOptionPane.showMessageDialog(null, "REGISTRO NO ELIMINADO");
        }
        else{
        JOptionPane.showMessageDialog(null, "REGISTRO ELIMINADO LOGICAMENTE");
        }
        try {
            db1.closeConnection();
        } catch (SQLException ex) {
            Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurpActionPerformed

    private void btnNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNominaActionPerformed
      
        String id = txtId.getText();
        String fecha = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime());;
        JFileChooser file = new JFileChooser();//Aqui se crea el seleccionador de archivos
       file.showOpenDialog(this);//Se pone la opcion para agregar
       
       
       
       String Actual = (String) jcbRegistro.getSelectedItem(); //Aqui se ve donde se registrara el archivo
       
       
       
       String Nombre = txtCarpeta.getText();//Aqui se tiene el nombre conforme lo agregado
        File archivo = file.getSelectedFile(); // Se crea la variable para poder manipular el archivo
           File directory = new File("C:\\BASEDATOS\\"+Actual+"\\"+Nombre+"\\"+"nomina\\");//Aqui se crea la carpeta del estado o usuario conforme no exista
         
           //Se mira que no sea null el archivo
           try{
               
           
           if(archivo !=null){
               
                 FileUtils.forceMkdir(directory);//Fuerza a que se creen los 2 directorios
           
             
             if(directory.exists()){
                  String Dest = "C:\\BASEDATOS\\"+Actual+"\\"+Nombre+"\\nomina\\"+archivo.getName();
                Path Destino = Paths.get(Dest);
                String Orig = archivo.getPath();
                Path Origen = Paths.get(Orig);
                Files.copy(Origen,Destino,REPLACE_EXISTING);
                JOptionPane.showMessageDialog(null,"Nomina Agregada correctamente");
                
                this.guardar(id, fecha, Dest);
              
                
                
                
             }
             
               
               
               
           }
           }catch (Exception e){
               
           }
        
        
        
        
        
        
    
        
        
        
        
        
        
    }//GEN-LAST:event_btnNominaActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
      int id = Integer.parseInt(Mostrar.txtId.getText());
       
        try {
              JasperReport archivo = JasperCompileManager.compileReport("C:\\reporte\\reporte1.jrxml");
        Map<String,Object> map = new HashMap<String, Object>();
     
        map.put("ID",id);
        map.put("logo1",Consultas.Imagen());
        map.put("Foto","C:\\BASEDATOS\\"+jcbRegistro.getSelectedItem()+"\\"+txtCarpeta.getText()+"\\"+txtRutaFoto1.getText());
        Conectar con = new Conectar("jdbc:mysql://localhost/prestige?serverTimezone=UTC");
    
      
        
        JasperPrint prin = JasperFillManager.fillReport(archivo,map,con.getConnection());
       // JasperExportManager.exportReportToPdfFile(prin,"reporte.pdf");
        JasperViewer ver = new JasperViewer(prin,false);
        ver.setTitle("COMPROBANTE DE REGISTRO PRESTIGE");
        ver.setVisible(true);
      
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"ERROR AL GENERAR REPORTE"+e);
        }
      
    
      
      
      
      
      
      
      
      
      
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarpetaActionPerformed
        String ruta="C:\\BASEDATOS\\"+jcbRegistro.getSelectedItem()+"\\"+txtCarpeta.getText();
        try {
           Desktop.getDesktop().open(new File(ruta));
        } catch (IOException ex) {
            Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Error al abrir la carpeta del usuario"+ex);
        }
        
    }//GEN-LAST:event_btnCarpetaActionPerformed

    private void txtNssKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNssKeyTyped
      int limite = 11;
        
        
        if(txtNss.getText().length() == limite ){
            evt.consume();
        }
        
        
        
        
    }//GEN-LAST:event_txtNssKeyTyped

    private void txtNuevonssKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNuevonssKeyTyped
     int limite = 11;
        
        
        if(txtNuevonss.getText().length() == limite ){
            evt.consume();
        }
    }//GEN-LAST:event_txtNuevonssKeyTyped

    private void btnGafeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGafeteActionPerformed

        if(Mostrar.txtPuesto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "NECESITA ESPECIFICAR EL PUESTO,NO PUEDE ESTAR VACIO", "ERROR", JOptionPane.ERROR_MESSAGE);
        
        return;
        }else{
            
            
            String puesto= null;
            
            puesto = txtPuesto.getText();
            
            
            
            int id = Integer.parseInt(Mostrar.txtId.getText());//Codigo para sacar el id de la persona
       
        try {
              JasperReport archivo = JasperCompileManager.compileReport("C:\\reporte\\reporte.jrxml");
        Map<String,Object> map = new HashMap<String, Object>();
     
        
     
        map.put("foto","C:\\BASEDATOS\\"+jcbRegistro.getSelectedItem()+"\\"+txtCarpeta.getText()+"\\"+txtRutaFoto1.getText());
        map.put("id",id);
        map.put("puesto",puesto);
        Conectar con = new Conectar("jdbc:mysql://localhost/prestige?serverTimezone=UTC");
    
      
        
        JasperPrint prin = JasperFillManager.fillReport(archivo,map,con.getConnection());
       // JasperExportManager.exportReportToPdfFile(prin,"reporte.pdf");
        JasperViewer ver = new JasperViewer(prin,false);
        ver.setTitle("Gafete Prestige");
        ver.setVisible(true);
      
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"ERROR AL GENERAR REPORTE"+e);
        }
      
        
        
        
        
        
        
        
        
         
            
        }
        
        
        
       
        
        
        
        
        
    }//GEN-LAST:event_btnGafeteActionPerformed

    private void txtRutaFoto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaFoto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaFoto1ActionPerformed

    private void txtPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuestoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnCarpeta;
    public static javax.swing.JButton btnEditar;
    public static javax.swing.JButton btnEliminar;
    public static final javax.swing.JButton btnGafete = new javax.swing.JButton();
    public static javax.swing.JButton btnNomina;
    public static javax.swing.JButton btnReporte;
    public static javax.swing.JPanel gafetesarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JComboBox<String> jcbOrigen;
    public static javax.swing.JComboBox<String> jcbRegistro;
    private javax.swing.JLabel lblFechaNac;
    private javax.swing.JLabel lblFechaNac1;
    private javax.swing.JLabel lblFechaNac10;
    private javax.swing.JLabel lblFechaNac11;
    private javax.swing.JLabel lblFechaNac12;
    private javax.swing.JLabel lblFechaNac13;
    private javax.swing.JLabel lblFechaNac2;
    private javax.swing.JLabel lblFechaNac3;
    private javax.swing.JLabel lblFechaNac4;
    private javax.swing.JLabel lblFechaNac5;
    private javax.swing.JLabel lblFechaNac6;
    private javax.swing.JLabel lblFechaNac7;
    private javax.swing.JLabel lblFechaNac8;
    private javax.swing.JLabel lblFechaNac9;
    public static javax.swing.JLabel lblFoto2;
    private javax.swing.JLabel lblMaterno;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPaterno;
    public static javax.swing.JLabel lblPuesto;
    public static javax.swing.JTextField txtCarpeta;
    public static javax.swing.JTextField txtComentarios;
    public static javax.swing.JTextField txtCorreo;
    public static javax.swing.JTextField txtCuenta;
    public static javax.swing.JTextField txtCurp;
    public static javax.swing.JTextField txtDireccion;
    public static javax.swing.JTextField txtEmergencia;
    public static javax.swing.JTextField txtEstudios;
    public static javax.swing.JTextField txtHistorial;
    public static javax.swing.JTextField txtId;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtNss;
    public static javax.swing.JTextField txtNuevonss;
    public static javax.swing.JTextField txtOtro;
    public static javax.swing.JTextField txtPuesto;
    public static javax.swing.JTextField txtRfc;
    public static javax.swing.JTextField txtRutaFoto1;
    public static javax.swing.JTextField txtRutas;
    public static javax.swing.JTextField txtStatus;
    public static javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
